import { useMutation } from "@apollo/client";
import { graphql } from "@gql/gql";

/* not longer needed as CreateUserInput is now coming from autogenerated files */
// import { User } from "@entities/User";

// interface CreateUserInput {
//   createUserInput: {
//     email: string;
//     password: string;
//   };
// }

const createUserDocument = graphql(`
  mutation CreateUser($createUserInput: CreateUserInput!) {
    createUser(createUserInput: $createUserInput) {
      _id
      email
    }
  }
`);

export function useCreateUser() {
  return useMutation(createUserDocument);
}
